name: Build and Test with CMake + Conan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ python3-pip ninja-build
          pip install conan

      - name: Conan Install
        run: |
          mkdir build
          conan install . --output-folder=build --build=missing

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build && ctest --output-on-failure
